version: "3.9"

services:
  gpupyter:
    build:
      context: .
      args:
        CUDA_BASE: nvidia/cuda:11.4.2-base-ubuntu20.04
        USER: gilles
        PASSWORD: 123
    image: gpupyter
    container_name: gpupyter
    restart: unless-stopped
    ports:
      - 8888:8888
    volumes:
      - gpupyter-data:/home/gilles
      - gpupyter-envs:/opt/conda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  gpupyter-data:
  gpupyter-envs: