version: "3.9"

services:
  gpupyter:
    build:
      context: .
      args:
        USER: gilles
    image: gpupyter
    restart: unless-stopped
    environment:
      - PASSWORD=sha1:d5710a7749b6:b374d929d2468d5f6524b3925fe73591ed116500
    ports:
      - 8888:8888
    volumes:
      - gpupyter-data:/home/gilles
      - gpupyter-envs:/opt/conda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    shm_size: 8G

volumes:
  gpupyter-data:
  gpupyter-envs:
    